package by.vss.exam.bean.manage.editCard;

public enum EditCardStage {
    SHOW_EDIT_USER_START_MESSAGE,

    SHOW_EDIT_CARD_START_MESSAGE,

    SHOW_FINAL_MESSAGE,
    SHOW_CONTROL_MENU,

//    RECEIVED_QUESTION,
//    RECEIVED_ANSWER,

    RECEIVED_EDITED_QUESTION,
    RECEIVED_EDITED_ANSWER,

    SAVED_CARD,

    SHOW_QUESTION,
    SHOW_ANSWER,
    SHOW_USER,
}
