package by.vss.exam.bean.manage;

public enum ManageStage {
    SHOW_START_MESSAGE,
    SHOW_FINAL_MESSAGE,

    RECEIVED_QUESTION,
    RECEIVED_ANSWER,

    RECEIVED_EDITED_QUESTION,
    RECEIVED_EDITED_ANSWER,

    SAVED_CARD,

    SHOW_QUESTION,
    SHOW_ANSWER,

}
